---
- name: Check if Ghost is installed
  ansible.builtin.file:
    path: "{{ ghost_base_dir }}/{{ item['dir'] }}/.ghost-cli"
    state: "file"
  register: ghost_installed
  ignore_errors: true

- name: Include Ghost Install Tasks
  include_tasks: ghost-install.yml
  when: ghost_installed is failed

- name: Load ghost-cli config
  ansible.builtin.slurp:
    src: "{{ ghost_base_dir }}/{{ item['dir'] }}/.ghost-cli"
  register: cli_file

- name: Pasre config json
  ansible.builtin.set_fact:
    ghost_cli: "{{ cli_file['content'] | b64decode | from_json }}"

- name: Include MySQL Database Tasks
  include_tasks: setup-mysql-database.yml
  vars:
    mysql: "{{ item['database']['connection'] }}"
  when: "item['database'] is defined and 'mysql' in item['database']['client']"

- name: Include s3 Storage Adapter Tasks
  include_tasks: setup-s3-storage.yml
  vars:
    storage: "{{ item['storage'] }}"
  when: item['storage'] is defined

- name: Include Upgrade Ghost Tasks
  include_tasks: ghost-upgrade.yml
  when: ghost_installed is succeeded

- name: Include Integrity Check Tasks
  include_tasks: ghost-integrity-check.yml

- name: Include Service Tasks
  include_tasks: ghost-service.yml
  when: item['type'] == "production"

- name: Run ghost start command
  become: true
  become_user: "{{ ghost_user }}"
  command:
    cmd: ghost start
    chdir: "{{ ghost_base_dir }}/{{ item['dir'] }}"
  register: ghost_started
  changed_when: "'Ghost is already running!' not in ghost_started['stdout']"
  when: item['state'] == "started"

- name: Run ghost stop command
  become: true
  become_user: "{{ ghost_user }}"
  command:
    cmd: ghost stop
    chdir: "{{ ghost_base_dir }}/{{ item['dir'] }}"
  when: item['state'] == "stopped"
