---
- name: "({{ item['name'] | default(item['id']) }}) Check for Ghost upgrade"
  become: true
  become_user: "{{ ghost_user }}"
  command:
    chdir: "{{ ghost_base_dir }}/{{ item['id'] }}"
    cmd: "ghost check-update"
  register: ghost_update_status
  changed_when: '"You\u0027re up to date!" not in ghost_update_status.stdout'

- name: "({{ item['name'] | default(item['id']) }}) Upgrade Ghost install"
  become: true
  become_user: "{{ ghost_user }}"
  command:
    chdir: "{{ ghost_base_dir }}/{{ item['id'] }}"
    cmd: ghost upgrade
  when: ghost_update_status.changed
