---
- name: "Check for Ghost upgrade: {{ item.dir }}"
  become: true
  become_user: "{{ ghost_user }}"
  command:
    chdir: "{{ ghost_base_dir }}/{{ item.dir }}"
    cmd: "ghost check-update"
  register: ghost_update_status
  changed_when: '"You\u0027re up to date!" not in ghost_update_status.stdout'

- name: "Upgrade Ghost install: {{ item.name }}"
  become: true
  become_user: "{{ ghost_user }}"
  command:
    chdir: "{{ ghost_base_dir }}/{{ item.dir }}"
    cmd: ghost upgrade
  when: ghost_update_status.changed
