---
- name: Ensure services is present
  template:
    src: templates/service.j2
    dest: "/lib/systemd/system/ghost_{{ item['dir'] }}.service"
    owner: guser
    group: ghost
    mode: 0644

- name: Ensure service is persent in ghost-cli config
  set_fact:
    ghost_cli: "{{ ghost_cli | combine({ 'name': item['dir'] }) }}"
  when: ghost_cli['name'] is not defined and ghost_cli['name'] != item['dir']

- name: Ensure ghost-cli config is up to date
  copy:
    content: "{{ ghost_cli | to_json }}"
    dest: "{{ ghost_base_dir }}/{{ item['dir'] }}/.ghost-cli"
    owner: guser
    group: ghost
    mode: 0664
