---
- name: Set config file name
  set_fact:
    config_env: "{% if item['type'] is defined and item['type'] == 'local' %}development{% else %}prodcution{% endif %}"

- name: Make sure config file is correct
  copy:
    content: "{{ lookup('template', 'templates/config.j2') | to_nice_json }}"
    dest: "{{ item['dir'] }}/config.{{ config_env }}.json"

- name: Make sure dev themes are linked
  when: item.themes_dev is defined
  file:
    path: "{{ item.dir }}/content/themes/{{ theme.name }}"
    src: "{{ theme.src }}"
    state: link
  ignore_errors: True
  loop: "{{ item.themes_dev }}"
  loop_control:
    loop_var: theme
