---
- name: Make sure config file is correct
  template:
    src: config.j2
    dest: "{{ item['dir'] }}/config.development.json"

- name: Make sure dev themes are linked
  when: item.themes_dev is defined
  file:
    path: "{{ item.dir }}/content/themes/{{ theme.name }}"
    src: "{{ theme.src }}"
    state: link
  ignore_errors: True
  loop: "{{ item.themes_dev }}"
  loop_control:
    loop_var: theme
