---
- name: Make sure install dir exsists
  file:
    path: "{{ ghost_base_dir }}/{{ item['id'] }}"
    state: directory
    owner: "{{ ghost_user }}"
    group: "{{ ghost_group }}"
    mode: 00775

- name: Run 'ghost install'
  become: true
  become_user: "{{ ghost_user }}"
  command:
    chdir: "{{ ghost_base_dir }}/{{ item['id'] }}"
    cmd: "ghost install --no-setup {% if item['local'] is defined and item['local'] %}local{% endif %} {% if item['version'] is defined %}{{item['version']}} --force{% endif %}"
