---
- name: "({{ item['name'] | default(item['id']) }}) Make sure config file is correct"
  copy:
    content: "{{ lookup('template', 'templates/config.j2') | to_json(indent=2, sort_keys=false) }}"
    dest: "{{ ghost_base_dir }}/{{ item['id'] }}/config.{{ install_type }}.json"
    owner: "{{ ghost_user }}"
    group: "{{ ghost_group }}"
    mode: 0664
  register: config_updated

- name: "({{ item['name'] | default(item['id']) }}) Make sure routes file is correct"
  copy:
    src: "{{ item['routes_file'] }}"
    dest: "{{ ghost_base_dir }}/{{ item['id'] }}/content/settings/routes.yaml"
    owner: "{{ ghost_group }}"
    group: "{{ ghost_group }}"
    mode: 0664
  when: item['routes_file'] is defined
  register: routes_updated

- name: "({{ item['name'] | default(item['id']) }}) Find all installed versions of Ghost"
  find:
    path: "{{ ghost_base_dir }}/{{ item['id'] }}/versions/"
    file_type: directory
  register: ghost_versions

- name: "({{ item['name'] | default(item['id']) }}) Identify the most current version of Ghost"
  set_fact:
    current_version: "{{ ghost_versions.files | sort(attribute='mtime') | last }}"

- name: "({{ item['name'] | default(item['id']) }}) Ensure ./current directory is linked correctly"
  file:
    path: "{{ ghost_base_dir }}/{{ item['id'] }}/current"
    src: "{{ current_version.path }}"
    state: link

- name: "({{ item['name'] | default(item['id']) }}) Ensure Casper theme is linked"
  file:
    path: "{{ ghost_base_dir }}/{{ item['id'] }}/content/themes/casper"
    src: "{{ ghost_base_dir }}/{{ item['id'] }}/current/content/themes/casper"
    state: link

- name: "({{ item['name'] | default(item['id']) }}) Ensure dev themes are linked"
  when: item.themes_dev is defined
  file:
    path: "{{ ghost_base_dir }}/{{ item['id'] }}/content/themes/{{ theme['name'] }}"
    src: "{{ theme['src'] }}"
    state: link
  ignore_errors: True
  loop: "{{ item['themes_dev'] }}"
  loop_control:
    loop_var: theme

- name: "({{ item['name'] | default(item['id']) }}) Ensure content dircetory has the correct permissions"
  shell:
    cmd: "chown -R ghost:ghost ./content"
    chdir: "{{ ghost_base_dir }}/{{ item['id'] }}"
  when: install_type == "production"

- name: "({{ item['name'] | default(item['id']) }}) Ensure all dircetories have the correct permissions"
  shell:
    cmd: "find ./ -type d ! -perm 00775 -print -exec chmod 00775 {} \\;"
    chdir: "{{ ghost_base_dir }}/{{ item['id'] }}"
  when: install_type == "production"
  register: directory_permissions
  changed_when: directory_permissions['stdout'] != ''

- name: "({{ item['name'] | default(item['id']) }}) Ensure all files have the correct permissions"
  shell:
    cmd: "find ./ ! -path './versions/*' -type f ! -perm 664 -print -exec chmod 664 {} \\;"
    chdir: "{{ ghost_base_dir }}/{{ item['id'] }}"
  when: install_type == "production"
  register: file_permissions
  changed_when: file_permissions['stdout'] != ''
