---
# tasks file for ghost-blog
- name: Include System Check Tasks
  include_tasks: system-check.yml

- name: Include User & Group setup Tasks
  include_tasks: setup-users-and-groups.yml
  when: ansible_user != ghost_user

- name: "Configure Instalation(s)"
  include_tasks: configure-ghost.yml
  loop: "{{ ghost_installs }}"
  loop_control:
    label: "{{ item.name | default(item['dir']) }}"
