---
# tasks file for ghost-blog
- name: Include System Check Tasks
  include_tasks: system-check.yml

- name: Include User & Group setup Tasks
  include_tasks: setup-users-and-groups.yml
  when: ansible_user_id != ghost_user

- name: "Configure Instalation(s)"
  include_tasks: configure-ghost.yml
  loop: "{{ ghost_installs }}"
  loop_control:
    label: "{{ item['name'] | default(item['id']) }}"

- name: Get ghost_user home dircetory
  become: true
  become_user: "{{ ghost_user }}"
  command: "echo $HOME"
  register: home_dir

- name: Ensure Global Ghost directory exsists
  file:
    path: "{{ home_dir['stdout'] }}/.ghost"
    owner: "{{ ghost_user }}"
    state: directory

- name: Ensure Global config is correct
  copy:
    content: "{{ lookup('template', 'templates/global-config.j2') | to_json(indent=2, sort_keys=false) }}"
    dest: "{{ home_dir['stdout'] }}/.ghost/config"
    owner: "{{ ghost_user }}"
    mode: 0664
