---
- name: Ensure database is present
  mysql_db:
    login_user: "{{ mysql['user'] | default('root') }}"
    login_password: "{{ mysql['password'] }}"
    login_host: "{{ mysql['host'] | default('localhost') }}"
    name: "{{ mysql['database'] | default(item['id'] | regex_replace('-|\\.','_')) }}_{%- if install_type == 'development' -%}dev{%- else -%}prod{%- endif -%}"
    state: present
