---
- name: "({{ item['name'] | default(item['id']) }}) Sanatize ghost_install id"
  set_fact:
    sanatized_id: "{{ item['id'] | regex_replace('-|\\.','_') }}"

- name: "({{ item['name'] | default(item['id']) }}) Set db_default_name"
  set_fact:
    db_default_name: "{{ sanatized_id }}_{%- if install_type == 'development' -%}dev{%- else -%}prod{%- endif -%}"

- name: "({{ item['name'] | default(item['id']) }}) Ensure database is present"
  mysql_db:
    login_user: "{{ mysql['user'] | default('root') }}"
    login_password: "{{ mysql['password'] }}"
    login_host: "{{ mysql['host'] | default('localhost') }}"
    name: "{{ mysql['database'] | default(db_default_name) }}"
    state: present
