---
- name: Create database
  mysql_db:
    login_user: "{{ mysql['user'] | default('root') }}"
    login_password: "{{ mysql['password'] }}"
    login_host: "{{ mysql['host'] | default(omit) }}"
    name: "{{ mysql['database'] }}"
    state: present
