---
- name: Ensue object storage bucket is present
  amazon.aws.s3_bucket:
    access_key: "{{ storage['accessKeyId'] }}"
    secret_key: "{{ storage['secretAccessKey'] }}"
    name: "{{ storage['bucket'] | default(item['id']) }}"
    state: present
    endpoint_url: "https://{{ storage['endpoint'] }}"

- name: Ensure npm storage adapter is installed
  become_user: "{{ ghost_user }}"
  npm:
    name: "{{ storage['npm_package'] }}"
    version: "{{ storage['npm_package_version'] | default('latest') }}"
    path: "{{ ghost_base_dir }}/{{ item['id'] }}"

- name: Ensure storage adapters dir is present
  file:
    path: "{{ ghost_base_dir }}/{{ item['id'] }}/content/adapters/storage/"
    owner: "{{ ghost_user }}"
    group: "{{ ghost_group }}"
    state: directory

- name: Ensure storage adapter files are linked
  file:
    src: "{{ ghost_base_dir }}/{{ item['id'] }}/node_modules/{{ storage['npm_package'] }}"
    dest: "{{ ghost_base_dir }}/{{ item['id'] }}/content/adapters/storage/{{ storage['npm_package'] }}"
    owner: "{{ ghost_user }}"
    group: "{{ ghost_group }}"
    state: link
