---
- name: Set homebrew path for Intel Mac
  update_fact:
    node_path: "/usr/local/{{node_path}}"
  when: ansible_distribution == "MacOSX"

- name: Set homebrew path for M1 Mac
  update_fact:
    node_path: "/opt/homebrew/{{node_path}}"
  when:
    - ansible_distribution == "MacOSX"
    - ansible_architecture == "arm64"

- name: Ensure ghost-cli is installed
  npm:
    global: true
    name: "ghost-cli"
    state: "latest"
  environment:
    PATH: "{{ node_path }}:{{ ansible_env.PATH }}"

- name: Ensure required python3 packages are installed
  pip:
    name:
      - PyMySQL
      - botocore
      - boto3
