---
- name: Set homebrew path for Intel Mac
  set_fact:
    homebrew_path: /usr/local/

- name: Set homebrew path for M1 Mac
  set_fact:
    homebrew_path: /opt/homebrew/
  when: ansible_architecture == "arm64"

- name: Ensure ghost-cli is installed
  npm:
    global: true
    name: "ghost-cli"
    state: "latest"
  environment:
    PATH: "{{ homebrew_path }}{{ node_path }}:{{ ansible_env.PATH }}"

- name: Ensure required python3 packages are installed
  pip:
    name:
      - PyMySQL
      - botocore
      - boto3
