---
- name: Ensure ghost-cli is installed
  npm:
    global: true
    name: "ghost-cli"
    state: "latest"

- name: Ensure required python3 packages are installed
  pip:
    name:
      - PyMySQL
      - botocore
      - boto3
