---
- name: Ensure ghost-cli is installed
  npm:
    global: true
    name: "ghost-cli"
    state: "latest"

- name: Ensure required python3 packages are installed
  pip:
    name:
      - PyMySQL
      - botocore
      - boto3

- name: Check if Ghost is installed
  file:
    path: "{{ ghost_base_dir }}/{{ item['dir'] }}/.ghost-cli"
    state: "file"
  loop: "{{ ghost_installs }}"
  loop_control:
    label: "{{ item.name | default(item['dir']) }}"
  register: ghost_installed
  changed_when: ghost_installed.state == "absent"
  failed_when: false
